# Makefile instructions found at https://bytes.usc.edu/cs104/wiki/makefile/
# g++ instructions from https://bytes.usc.edu/cs104/wiki/gcc/
program:
	g++ -std=c++17 -pedantic -Wall -Wshadow -O2 -o main *.cpp

clean:
	rm main
