# Makefile instructions found at https://bytes.usc.edu/cs104/wiki/makefile/
# g++ instructions from https://bytes.usc.edu/cs104/wiki/gcc/
program:
	g++ -std=c++17 -pedantic -Wall -Wextra -Werror -Wshadow -Wsign-conversion -g -O2 *.cpp

clean:
	rm a.out
	rm -r a.out.dSYM